cargo-features = ["edition2024"]

[package]
name = "commitia"
version = "0.0.2"
edition = "2021"
authors = ["linuxmobile <bdiez19@gmail.com>"]
description = "Commit message generator inspired by Argentine slang"
homepage = "https://commitia.linu.dev"
exclude = ["assets/*"]
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["git", "commit", "cli", "commitizen", "conventional-commits"]

[dependencies]
aes = "0.8.4"
anyhow = "1.0.86"
async-std = { version = "1.12.0", features = ["attributes"] }
asyncgit = "0.26.3"
block-padding = "0.3.3"
cbc = "0.1.2"
clap = { version = "4.5.16", features = ["derive"] }
crossterm = "0.28.1"
dirs = "5.0.1"
google-generative-ai-rs = { version = "0.3.2", features = ["beta"] }
hex = "0.4.3"
hex-literal = "0.4.1"
openssl-sys = "0.9.103"
ratatui = "0.28.0"
serde = "1.0.208"
serde_json = "1.0.126"
tui-big-text = "0.6.0"
tui-prompts = "0.4.0"
tui-widgets = "0.3.0"
webbrowser = "1.0.1"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
strip = "debuginfo"

[profile.dev]
opt-level = 1

[profile.dev.package."ratatui"]
opt-level = 3
